### ISSUE TITLE
SDK Documentation

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/tools#11]
We need to set up a good documentation workflow.

We should have two sets of docs:
 - JSDoc based documentation, generated from new releases.
 - Higher level usage docs for developers using the SDK.

For the JSDocs we will need to ensure there is high quality documentation strings placed on all external functions. Ideally, a developer should never need to read the code to understand the interface of a function or what it does.

**Comment by saboonikhil** [comment]
Closing this in favour of new [V2 documentation](https://docs.zeitgeist.pm/docs/build/sdk/v2/introduction).
