### ISSUE TITLE
Add a query function for pools' liquidity

### ISSUE THREAD

**Issue by Whisker17** [zeitgeistpm/tools#142]
I hope there is an indicator that reflects the popularity of the market. I think the liquidity of the pool can well reflect this.

I suggest adding a query function for pools to get the amount of balances inside the pool accounts.

**Comment by saboonikhil** [comment]
This should be visible following the subsquid implementation on spot price history of the pool. Currently, we have token/ztg balances available for all accounts (with few minor discrepancies) at the [graphql node](https://processor.zeitgeist.pm/graphql).

**Comment by Whisker17** [comment]
What I want to get is a stake amount of a pool updated in real time, seems not this, right?
![image](https://user-images.githubusercontent.com/12571049/151702284-b05b006c-2f86-44a0-a4e9-5702ea54428f.png)


> This should be visible following the subsquid implementation on spot price history of the pool. Currently, we have token/ztg balances available for all accounts (with few minor discrepancies) at the [graphql node](https://processor.zeitgeist.pm/graphql).

**Comment by saboonikhil** [comment]
> What I want to get is a stake amount of a pool updated in real time, seems not this, right? ![image](https://user-images.githubusercontent.com/12571049/151702284-b05b006c-2f86-44a0-a4e9-5702ea54428f.png)
> 
> > This should be visible following the subsquid implementation on spot price history of the pool. Currently, we have token/ztg balances available for all accounts (with few minor discrepancies) at the [graphql node](https://processor.zeitgeist.pm/graphql).

Yep, not yet. I will let you know when this is available.

**Comment by saboonikhil** [comment]
Does the issue https://github.com/zeitgeistpm/zeitgeist-subsquid/issues/69 sound similar to this?

The change can be fetched using:
```
query MyQuery {
  pools {
    poolId
    volume
    ztgQty
  }
}
```
where `volume` is the total amount of ZTG that has moved through a market's liquidity pool in its lifecycle and `ztgQty` is the amount of ZTG currently present in the pool.

**Comment by Whisker17** [comment]
> Does the issue [zeitgeistpm/zeitgeist-subsquid#69](https://github.com/zeitgeistpm/zeitgeist-subsquid/issues/69) sound similar to this?
> 
> The change can be fetched using:
> 
> ```
> query MyQuery {
>   pools {
>     poolId
>     volume
>     ztgQty
>   }
> }
> ```
> 
> where `volume` is the total amount of ZTG that has moved through a market's liquidity pool in its lifecycle and `ztgQty` is the amount of ZTG currently present in the pool.

Yep, sounds great
