### ISSUE TITLE
After upgrading @polkadot/* libraries in 0.3.10 sdk is not usable any more in the web app

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/tools#145]
Reproduce:

In `zeitgeistpm/proto` repository
1. update `@zeitgeistom/sdk` version in `package.json` to 0.3.10
2. run `yarn install`
3. run yarn dev

Following error shows up three times:
```
error - ./node_modules/@polkadot/hw-ledger/packageInfo.js
Module parse failed: Unexpected token (6:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export const packageInfo = {
|   name: '@polkadot/hw-ledger',
>   path: new URL('.', import.meta.url).pathname,
|   type: 'esm',
|   version: '8.3.1'
```

**Comment by saboonikhil** [comment]
Just for reference: In the same version, SDK was upgraded to support `Polkadot v6.11.1` - https://github.com/zeitgeistpm/tools/pull/140/commits/c0b5848480d87f25de0e23a2b8eb28d4a042f2e5

**Comment by TvrtkoM** [comment]
We found what was wrong. The issue seems to be with web-app.
