### ISSUE TITLE
Replace current max limit for graphql queries with some reasonable value

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/tools#167]
Currently queries that need to fetch all data without limit need to override default subsquid limit (50).
While `Math.pow(31, 2) - 1` is actual max limit for query results it should be decreased to some reasonable value (e.g. 5000)

**Comment by saboonikhil** [comment]
The default limit seem to have been removed in `v5` and I'm able to see more than 200 objects in a single query. Not sure if this is dynamic, however, just a heads up before we add any hard changes.
