### ISSUE TITLE
[SDK] Add methods for fetching markets by certain attributes and by page

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/tools#19]
We need methods for fetching a page of markets (20 at a time) for certain attributes:

- Most recently created
- Ending soon
- By trade volume (popularity)
- By liquidity

**Comment by morkeltry** [comment]
partial solution: `zgcli getAllMarkets --filter md1 md2 md3 md4`
where md_ = some property on `ExtendedMarketResponse` type which exists

**Comment by saboonikhil** [comment]
@lsaether I think the recent subsquid implementation in the sdk adds all these features. Are we good here?
