### ISSUE TITLE
`Models.filterMarkets` returning different results with same params and no change to the db.

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/tools#202]
When I call the function `Models.filterMarkets` it produces wildly different `result` and `count` every time, sometimes several results, sometimes none, and sometimes the count says a positive number but the results array is empty.

Related issue: zeitgeistpm/ui#132

_**Marked as critical as it is one of the core functions of the app to be released, to be able to view markets in reliable way.**_

**Comment by saboonikhil** [comment]
Can you share an example?

What are the params being sent and thus the result obtained?

**Comment by yornaath** [comment]
So I did a couple of refreshes and inspected the network logs. I diffed the queries and the only param that changed was the `end_gt` variable, but the results changed. Sometimes returning one result, sometimes none and sometimes several.

**I also did some debugging with postmant, and the query seemed to return the same result when the cookie stayed the same. When I cleared cookied for the domain the result changed and the result stayed the same for subsequent results until I cleared the cookie again.**

**Endpoint:** https://processor.bsr.zeitgeist.pm/graphql

**Query:**
```json
{
  "query": "\n      query MarketPage(\n        \n        $tags: [String!]\n        \n        $pageSize: Int\n        $offset: Int!\n        $orderByQuery: [MarketOrderByInput!]\n        $creator: String\n        $oracle: String\n        $end_gt: BigInt, $end_lt: BigInt,\n        $minPoolId: Int\n        $marketIds: [Int!]\n        $assets: [String!]\n      ) {\n        markets(\n          where: { OR: [, {\n      status_eq: \"Active\"\n      slug_contains: \"\"\n      tags_containsAll: $tags\n      creator_eq: $creator\n      oracle_eq: $oracle\n      end_gt: $end_gt\n      end_lt: $end_lt\n      poolId_gte: $minPoolId\n      marketId_in: $marketIds\n      outcomeAssets_containsAny: $assets\n    } ] }\n          limit: $pageSize\n          offset: $offset\n          orderBy: $orderByQuery\n        ) {\n          ...MarketDetails\n        }\n      }\n      \n  fragment MarketDetails on Market {\n    marketId\n    description\n    end\n    creator\n    creatorFee\n    creation\n    oracle\n    question\n    slug\n    img\n    tags\n    status\n    scoringRule\n    resolvedOutcome\n    poolId\n    marketType {\n      categorical\n      scalar\n    }\n    period {\n      block\n      timestamp\n    }\n    report {\n      outcome {\n        categorical\n        scalar\n      }\n      at\n      by\n    }\n    mdm {\n      Authorized: authorized\n      Court: court\n      SimpleDisputes: simpleDisputes\n    }\n    categories {\n      ticker\n      name\n      color\n    }\n  }\n\n    ",
  "variables": {
    "statuses": [],
    "pageSize": 5,
    "offset": 0,
    "orderByQuery": "marketId_DESC",
    "end_gt": 1657187718024,
    "minPoolId": 0,
    "marketIds": [
      0, 1, 2, 3, 4, 5, 6, 7, 13, 14, 15, 18, 21, 22, 23, 24, 25, 29, 30, 31,
      32, 33, 34, 35, 36, 40, 41, 44, 46, 47, 48, 49, 54, 55, 56, 59, 60, 61,
      62, 63, 64, 65, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
      82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 93, 94, 95, 96, 97, 98, 99, 100,
      101, 102, 103, 104, 106, 107, 108, 109, 110, 111, 113, 114, 115, 116, 117,
      118, 119, 120, 121, 122, 123, 125, 127, 128, 129, 130, 131, 132, 133, 136,
      138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 153, 154,
      155, 156, 157, 160, 163, 164, 166, 167, 168, 169, 170, 171, 172, 173, 174,
      175, 176, 177, 178, 179, 180, 181, 183, 184, 185, 186, 187, 188, 189, 190,
      192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 203, 204, 205, 206, 207,
      208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222,
      223, 224, 225, 226, 227, 228, 229, 230, 231, 233, 234, 235, 236, 237, 238,
      240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 254, 255, 256,
      259, 260, 261, 262, 263, 264, 267, 268, 269, 270, 271, 272, 273, 274, 275,
      276, 277, 278, 279, 280, 281, 282, 285, 286, 287, 288, 289, 290, 291, 292,
      293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307,
      308, 309, 310, 311, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323,
      324, 325, 326, 327, 329, 330, 331, 332, 336, 337, 338, 339, 340, 341, 342,
      343, 345, 346, 347, 348, 349, 350, 351, 353, 354, 355, 356, 357, 358, 359,
      360, 361, 362, 363, 364, 365, 366, 367, 369, 370, 371, 372, 373, 374, 375,
      376, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391,
      392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406,
      407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419
    ]
  }
}

```

Sometimes I also receive some errors for the exact same query:

```json
{
    "errors": [
        {
            "message": "relation \"market\" does not exist",
            "locations": [
                {
                    "line": 16,
                    "column": 9
                }
            ],
            "path": [
                "markets"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "length": 106,
                    "name": "error",
                    "severity": "ERROR",
                    "code": "42P01",
                    "position": "913",
                    "file": "parse_relation.c",
                    "line": "1191",
                    "routine": "parserOpenTable",
                    "stacktrace": [
                        "error: relation \"market\" does not exist",
                        "    at Parser.parseErrorMessage (/root/zeitgeist-subsquid/node_modules/pg-protocol/dist/parser.js:287:98)",
                        "    at Parser.handlePacket (/root/zeitgeist-subsquid/node_modules/pg-protocol/dist/parser.js:126:29)",
                        "    at Parser.parse (/root/zeitgeist-subsquid/node_modules/pg-protocol/dist/parser.js:39:38)",
                        "    at Socket.<anonymous> (/root/zeitgeist-subsquid/node_modules/pg-protocol/dist/index.js:11:42)",
                        "    at Socket.emit (node:events:390:28)",
                        "    at addChunk (node:internal/streams/readable:315:12)",
                        "    at readableAddChunk (node:internal/streams/readable:289:9)",
                        "    at Socket.Readable.push (node:internal/streams/readable:228:10)",
                        "    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```

**Comment by TvrtkoM** [comment]
I've been trying to test issues related to querying market data with cli commands e.g.
`yarn cli queryFilteredMarkets --statuses Active --page-size 5 --ordering asc` and I get the same result every time, which corresponds with the data from devtools in the browser.

The market collection inside the nextjs app, doesn't show the correct order of the markets when compared with the data from graphql response.

However, there is new `Closed` status on the markets as of node version `0.3.4` and we should use that instead of manually calculating `Ended` in different places across different repositories (subsquid, tools, ui), especially since the calculation isn't right wrong for markets with periods set as block numbers since each block is never exactly 12 seconds long.

So I'd rather rewrite the whole querying part once the subsquid is indexing the new `Closed` status, than making changes on the same codebase twice.

**Comment by TvrtkoM** [comment]
There is however something strange happening with graphql results as @yornaath mentioned.
The, almost same query sometimes returns only one result, sometimes returnes 4 and sometimes 5.

Try landing on `https://staging.zeitgeist.pm/` multiple times (remove query params from the url)

**Comment by TvrtkoM** [comment]
Above can be reproduced on https://processor.bsr.zeitgeist.pm/graphql

with following query:
```

      query MarketPage(
        
        $tags: [String!]
        
        $pageSize: Int
        $offset: Int!
        $orderByQuery: [MarketOrderByInput!]
        $creator: String
        $oracle: String
        $end_gt: BigInt, $end_lt: BigInt,
        $minPoolId: Int
        $marketIds: [Int!]
        $assets: [String!]
      ) {
        markets(
          where: { OR: [, {
      status_eq: "Active"
      slug_contains: ""
      tags_containsAll: $tags
      creator_eq: $creator
      oracle_eq: $oracle
      end_gt: $end_gt
      end_lt: $end_lt
      poolId_gte: $minPoolId
      marketId_in: $marketIds
      outcomeAssets_containsAny: $assets
    } ] }
          limit: $pageSize
          offset: $offset
          orderBy: $orderByQuery
        ) {
          ...MarketDetails
        }
      }
      
  fragment MarketDetails on Market {
    marketId
    description
    end
    creator
    creatorFee
    creation
    oracle
    question
    slug
    img
    tags
    status
    scoringRule
    resolvedOutcome
    poolId
    marketType {
      categorical
      scalar
    }
    period {
      block
      timestamp
    }
    report {
      outcome {
        categorical
        scalar
      }
      at
      by
    }
    mdm {
      Authorized: authorized
      Court: court
      SimpleDisputes: simpleDisputes
    }
    categories {
      ticker
      name
      color
    }
  }
```

and following query variables:

```
{
  "statuses": [],
  "pageSize": 5,
  "offset": 0,
  "orderByQuery": "marketId_DESC",
  "end_gt": 1658493224915,
  "minPoolId": 0,
  "marketIds": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    13,
    14,
    15,
    18,
    21,
    22,
    23,
    24,
    25,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    40,
    41,
    44,
    46,
    47,
    48,
    49,
    54,
    55,
    56,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
    106,
    107,
    108,
    109,
    110,
    111,
    113,
    114,
    115,
    116,
    117,
    118,
    119,
    120,
    121,
    122,
    123,
    125,
    127,
    128,
    129,
    130,
    131,
    132,
    133,
    136,
    138,
    139,
    140,
    141,
    142,
    143,
    144,
    145,
    146,
    147,
    148,
    149,
    150,
    153,
    154,
    155,
    156,
    157,
    160,
    163,
    164,
    166,
    167,
    168,
    169,
    170,
    171,
    172,
    173,
    174,
    175,
    176,
    177,
    178,
    179,
    180,
    181,
    183,
    184,
    185,
    186,
    187,
    188,
    189,
    190,
    192,
    193,
    194,
    195,
    196,
    197,
    198,
    199,
    200,
    201,
    203,
    204,
    205,
    206,
    207,
    208,
    209,
    210,
    211,
    212,
    213,
    214,
    215,
    216,
    217,
    218,
    219,
    220,
    221,
    222,
    223,
    224,
    225,
    226,
    227,
    228,
    229,
    230,
    231,
    233,
    234,
    235,
    236,
    237,
    238,
    240,
    241,
    242,
    243,
    244,
    245,
    246,
    247,
    248,
    249,
    250,
    251,
    254,
    255,
    256,
    259,
    260,
    261,
    262,
    263,
    264,
    267,
    268,
    269,
    270,
    271,
    272,
    273,
    274,
    275,
    276,
    277,
    278,
    279,
    280,
    281,
    282,
    285,
    286,
    287,
    288,
    289,
    290,
    291,
    292,
    293,
    294,
    295,
    296,
    297,
    298,
    299,
    300,
    301,
    302,
    303,
    304,
    305,
    306,
    307,
    308,
    309,
    310,
    311,
    313,
    314,
    315,
    316,
    317,
    318,
    319,
    320,
    321,
    322,
    323,
    324,
    325,
    326,
    327,
    329,
    330,
    331,
    332,
    336,
    337,
    338,
    339,
    340,
    341,
    342,
    343,
    345,
    346,
    347,
    348,
    349,
    350,
    351,
    353,
    354,
    355,
    356,
    357,
    358,
    359,
    360,
    361,
    362,
    363,
    364,
    365,
    366,
    367,
    369,
    370,
    371,
    372,
    373,
    374,
    375,
    376,
    378,
    379,
    380,
    381,
    382,
    383,
    384,
    385,
    386,
    387,
    388,
    389,
    390,
    391,
    392,
    393,
    394,
    395,
    396,
    397,
    398,
    399,
    400,
    401,
    402,
    403,
    404,
    405,
    406,
    407,
    408,
    409,
    410,
    411,
    412,
    413,
    414,
    415,
    416,
    417,
    418,
    419,
    420
  ]
}
```

**Comment by saboonikhil** [comment]
> [
>     0,
>     1,
>     2,
>     3,
>     4,
>     5,
>     6,
>     7,
>     13,
>     14,
>     15,
>     18,
>     21,
>     22,
>     23,
>     24,
>     25,
>     29,
>     30,
>     31,
>     32,
>     33,
>     34,
>     35,
>     36,
>     40,
>     41,
>     44,
>     46,
>     47,
>     48,
>     49,
>     54,
>     55,
>     56,
>     59,
>     60,
>     61,
>     62,
>     63,
>     64,
>     65,
>     68,
>     69,
>     70,
>     71,
>     72,
>     73,
>     74,
>     75,
>     76,
>     77,
>     78,
>     79,
>     80,
>     81,
>     82,
>     83,
>     84,
>     85,
>     86,
>     87,
>     88,
>     89,
>     90,
>     91,
>     93,
>     94,
>     95,
>     96,
>     97,
>     98,
>     99,
>     100,
>     101,
>     102,
>     103,
>     104,
>     106,
>     107,
>     108,
>     109,
>     110,
>     111,
>     113,
>     114,
>     115,
>     116,
>     117,
>     118,
>     119,
>     120,
>     121,
>     122,
>     123,
>     125,
>     127,
>     128,
>     129,
>     130,
>     131,
>     132,
>     133,
>     136,
>     138,
>     139,
>     140,
>     141,
>     142,
>     143,
>     144,
>     145,
>     146,
>     147,
>     148,
>     149,
>     150,
>     153,
>     154,
>     155,
>     156,
>     157,
>     160,
>     163,
>     164,
>     166,
>     167,
>     168,
>     169,
>     170,
>     171,
>     172,
>     173,
>     174,
>     175,
>     176,
>     177,
>     178,
>     179,
>     180,
>     181,
>     183,
>     184,
>     185,
>     186,
>     187,
>     188,
>     189,
>     190,
>     192,
>     193,
>     194,
>     195,
>     196,
>     197,
>     198,
>     199,
>     200,
>     201,
>     203,
>     204,
>     205,
>     206,
>     207,
>     208,
>     209,
>     210,
>     211,
>     212,
>     213,
>     214,
>     215,
>     216,
>     217,
>     218,
>     219,
>     220,
>     221,
>     222,
>     223,
>     224,
>     225,
>     226,
>     227,
>     228,
>     229,
>     230,
>     231,
>     233,
>     234,
>     235,
>     236,
>     237,
>     238,
>     240,
>     241,
>     242,
>     243,
>     244,
>     245,
>     246,
>     247,
>     248,
>     249,
>     250,
>     251,
>     254,
>     255,
>     256,
>     259,
>     260,
>     261,
>     262,
>     263,
>     264,
>     267,
>     268,
>     269,
>     270,
>     271,
>     272,
>     273,
>     274,
>     275,
>     276,
>     277,
>     278,
>     279,
>     280,
>     281,
>     282,
>     285,
>     286,
>     287,
>     288,
>     289,
>     290,
>     291,
>     292,
>     293,
>     294,
>     295,
>     296,
>     297,
>     298,
>     299,
>     300,
>     301,
>     302,
>     303,
>     304,
>     305,
>     306,
>     307,
>     308,
>     309,
>     310,
>     311,
>     313,
>     314,
>     315,
>     316,
>     317,
>     318,
>     319,
>     320,
>     321,
>     322,
>     323,
>     324,
>     325,
>     326,
>     327,
>     329,
>     330,
>     331,
>     332,
>     336,
>     337,
>     338,
>     339,
>     340,
>     341,
>     342,
>     343,
>     345,
>     346,
>     347,
>     348,
>     349,
>     350,
>     351,
>     353,
>     354,
>     355,
>     356,
>     357,
>     358,
>     359,
>     360,
>     361,
>     362,
>     363,
>     364,
>     365,
>     366,
>     367,
>     369,
>     370,
>     371,
>     372,
>     373,
>     374,
>     375,
>     376,
>     378,
>     379,
>     380,
>     381,
>     382,
>     383,
>     384,
>     385,
>     386,
>     387,
>     388,
>     389,
>     390,
>     391,
>     392,
>     393,
>     394,
>     395,
>     396,
>     397,
>     398,
>     399,
>     400,
>     401,
>     402,
>     403,
>     404,
>     405,
>     406,
>     407,
>     408,
>     409,
>     410,
>     411,
>     412,
>     413,
>     414,
>     415,
>     416,
>     417,
>     418,
>     419,
>     420
>   ]

The processor was on a restart loop due to a bug (unmatched types). Consequently, the database was being refreshed every hour or so. This went unnoticed, so going forward, we will have notification system in place so that the error can be neutralised (without continuous restarts)

I have pushed the stable code and now getting details for 4 markets on this query.
