### ISSUE TITLE
Create a consistent and explanatory schema for error reporting in SDK

### ISSUE THREAD

**Issue by morkeltry** [zeitgeistpm/tools#39]
Currently, CLI/ SDK reports errors in at least four different ways to the user:

#### Unhandled Promise Rejection, with error type & message
The most disconcerting for the user!
Only example found:
```
2021-04-29 10:42:02        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
2021-04-29 10:42:02             DRR: Error: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
```
Apparently thrown from `@polkadot/rpc-provider/`
Error is caught but interruption prevents `unsub` being called (so program hangs)

#### Errors thrown by SDK, with error message
These look appropriate for now
(but also 

```  
Error: Market with market id 1 does not exist. (ie rejected or cancelled)
```

#### `ExtrinsicFailed` reported through SDK, with `{module, index}` populated
This could be improved by SDK having an index of`{module, index}` ->  Error
```
    ' {"applyExtrinsic":1}: system.ExtrinsicFailed::("index":3,"error":2 ...
```
The format perhaps should be merged with that of SDK errors?

#### `ExtrinsicFailed` reported through SDK, with `{module, index}` incomplete
```
    ' {"applyExtrinsic":1}: system.ExtrinsicFailed:: [{"other":null} .... 
```
Need to diagnose what these signify :/
(this one occurred attempting to `cancel_market`, but the market was previously approved)

**Comment by lsaether** [comment]
#54
