### ISSUE TITLE
[monorepo] Release schedule and checklists

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/tools#45]
We need to start having regular, stable releases of the SDK, CLI, and other libraries in this monorepo. If we use the CI, we can just automate releases whenever something is merged to `main`. It would also be nice to have preview releases made from PRs, since we can test new features without needing to merge to main.

- [ ] Decide on how releases should be made, at what frequency, and how.
- [ ] Add CI scripts to help with releases using lerna.

**Comment by saboonikhil** [comment]
Taken care of by the new sdk
