### ISSUE TITLE
pin down undefined behaviour in @polkadot/api

### ISSUE THREAD

**Issue by morkeltry** [zeitgeistpm/tools#50]
(lower priority than it sounds ;) )

`fetchMarketData` should never receive no or undefined `marketId`, however during debugging, it did, resulting in 
the `marketId` parameter to `api.query.predictionMarkets.markets(marketId)` being undefined.

`api` did not throw but provided a trivial response.
May be worth investigating...

**Comment by lsaether** [comment]
will re-open if reproduced
