### ISSUE TITLE
CLI or standalone script to diff type definitions

### ISSUE THREAD

**Issue by morkeltry** [zeitgeistpm/tools#61]
to compare,
eg: latest npm version, latest version on this repo, current SDK active in locally installed `type-defs` package and somehow the cookie/ querystring/ page `<input>` element in polkadot.js.org/apps

Also [document the process](https://github.com/zeitgeistpm/documentation/issues/14)!

**Comment by lsaether** [comment]
Is this complete?

**Comment by lsaether** [comment]
We can start versioning types in the type definitions if this becomes an issue.
