### ISSUE TITLE
pin down input types to `poolJoinWithExactAssetAmount`, `joinPoolMultifunc`

### ISSUE THREAD

**Issue by morkeltry** [zeitgeistpm/tools#63]
for the asset name,
 `poolJoinWithExactAssetAmount` uses `any` (unsatisafactory)
 `joinPoolMultifunc` has inherited the use of a type which is an alias for `string` (now wrong)

Allow conversion of string input into `AssetId` (which will replace `string` alias type `AssetIdStringForTempCompatibility`)

**Comment by lsaether** [comment]
Please make the individual functions for `poolJoin*` before doing smth like `joinPoolMultiFunc` I think one functions that tries to juggle a bunch of different types of input is more confusing than well specified independent functions.

**Comment by morkeltry** [comment]
See https://github.com/zeitgeistpm/tools/pull/77 & https://github.com/zeitgeistpm/tools/pull/79
