### ISSUE TITLE
Replace existing code to create `AssetID`s with `api.createType("Asset", ...)` where possible

### ISSUE THREAD

**Issue by morkeltry** [zeitgeistpm/tools#65]
eg in `AssetIdFromString`:

`return { ztg: null };`
could be like:

```
const asset = '{ ztg: null }';
const assetJson = JSON.parse(asset);
const assetType = api.createType("Asset", assetJson);
assert(assetType.isZtg, true);
```

**Comment by lsaether** [comment]
Actually, we should use `Asset` type everywhere an asset is being used. And I think we should be handling input in a different way so we don't have to type "CategoricalOutcome(1,2)" on the CLI. I don't think there are many use cases where we need to be typing out the Asset type on CLI, instead we should handle this differently. For example, we either take the `index` of the asset we want, or the `category` for the asset we want.
