### ISSUE TITLE
[SDK] `fetchPoolSpotPrices*` should use `Asset` for input

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/tools#66]
We should change `fetchPoolSpotPrices*` to use the `Asset` type for input.

**Comment by morkeltry** [comment]
##### Issue was previously named: fetchPoolSpotPrices* should use `Asset` for input.

All functions accepting `asset___` and simliar should accept `Asset` type and this can be pulled directly from `type-defs`.
I propose to alternatively accept string, to be converted to `asset` else error.

Many functions are using `asset: string` as input type, expecting a stringified version of whatever `Asset` currently is.

`joinPoolMultiFunc` is using `AssetIdStringForTempCompatibility` in `PoolJoinOpts`
`PoolJoinOpts` can be further rationalised  - make separate issue.

**Comment by morkeltry** [comment]
Done in https://github.com/zeitgeistpm/tools/pull/77 & https://github.com/zeitgeistpm/tools/pull/79 for `Asset`.
Not for `Balance` (but these are `number`)
