### ISSUE TITLE
My network node id is declared as a variable but it's not used when docker run

### ISSUE THREAD

**Issue by Darbakearg** [zeitgeistpm/tools#70]
I've generated a key for a permanent node id on WSL but my Local node identity is another one.

I used this docker image : fb127223ea8990bb27819dbbb9b15a46d7ffea73

Variables seems to be OK :

$ZEITGEIST_KEY_PATH=/root/.zeitgeist
$ZEITGEIST_KEY_NAME=12D...........bu

I would like to know how to configure a specific node ID for my node ?
I'm not getting good results with this procedure: https://docs.zeitgeist.pm/battery-park 

Thanks

**Comment by sea212** [comment]
Solved in discord chat.

**Comment by Darbakearg** [comment]
> 
> 
> Solved in discord chat.

Thank you @sea212 !
